sudo: required
language: python
python: 2.7

env:
  - PREPARED_STATEMENTS=0
  - PREPARED_STATEMENTS=1


services:
  - docker

before_install:
  - docker-compose --version
  - docker-compose --project-name django-multitenant up -d
  - ./scripts/wait_postgres.sh localhost 5600 localhost 5601 localhost 5602


install: pip install tox

script:
  - tox