sudo: required
language: python
python: 2.7

env:
  - PREPARED_STATEMENTS=0
  - PREPARED_STATEMENTS=1


services:
  - docker

before_install:
  - docker-compose up -d

install: pip install tox

script:
  - tox